language: php
php:

  - 7.0

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  before_deploy:
  - cd build

deploy:
    skip_cleanup: true
   verbose: true
  provider: heroku
  api_key:
    secure: "315f090b-ac15-4a3a-9d07-e74629df2c86"
