
language: php

php:
  - 5.2
install: php vendor/vendors.php
deploy:
  skip_cleanup: true

  provider: azure_web_apps
  username: "MatiasRJaime"
  password: "maraja96"
  site: "https://perrosmatias.azurewebsites.net/"
