language: php
php:

  - 7.0

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
deploy:
  provider: azure_web_apps
  username: MatiasRJaime
  password: maraja96
  site: https://perrosmatias.azurewebsites.net/
