language: php
php:

  - 7.0

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  before_deploy:
  - cd build

deploy:
    skip_cleanup: true
  verbose: true
  provider: azure_web_apps
  username: MatiasRJaime
  password: maraja96
  site: https://perrosmatias.azurewebsites.net/
